from datetime import UTC, datetime

from sqlalchemy import JSON, Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from app.core.database import Base


class Quiz(Base):
    """
    Quiz model storing quiz information and questions.

    Supports both STATIC quizzes (seeded in DB, reused for all students)
    and DYNAMIC quizzes (generated on-demand by the LLM for a specific
    student and concept). The `source` column distinguishes the two.
    """
    __tablename__ = "quiz"

    id = Column(Integer, primary_key=True, index=True)
    titre = Column(String(255), nullable=False)
    module = Column(String(255), nullable=False, index=True)
    difficulte = Column(String(50), nullable=False)  # easy, medium, hard
    questions = Column(JSON, nullable=False)  # Array of question objects
    date_creation = Column(DateTime, default=lambda: datetime.now(UTC), nullable=False)

    # --- Dynamic-quiz columns (NEW for Phase 2 Step 1) ---
    # source = "static" (seeded)  or  "generated" (produced by the LLM)
    source = Column(String(20), nullable=False, default="static", index=True)
    # If source="generated" : student who requested the generation.
    # Nullable because static quizzes have no owner.
    etudiant_generateur_id = Column(
        Integer, ForeignKey("etudiants.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    # Neo4j concept targeted by the quiz (e.g.: "concept_lagrange")
    concept_neo4j_id = Column(String(255), nullable=True, index=True)
    # Seed used for diversity (timestamp or hash)
    seed = Column(String(64), nullable=True)

    # ============================================================
    # mode = "adaptive" (default, updates the mastery)
    #     or "practice" (free practice, does NOT affect the mastery)
    # ============================================================
    # We encode the pedagogical INTENT at the moment the quiz is created.
    # The submit endpoint reads this field to decide whether or not to call
    # update_mastery_from_evaluations(). This is the requested pedagogical
    # separation : adaptive quizzes make progress, practice quizzes allow
    # training without risking hurting your progression.
    #
    # Why on Quiz and not on QuizResult ? Because the mode is decided at
    # GENERATION time (auto vs manual difficulty selection), not at
    # submission time. Putting it on Quiz keeps the source-of-truth
    # consistency and avoids the same quiz being submitted twice with
    # different modes.
    mode = Column(String(20), nullable=False, default="adaptive", index=True)

    # Relationships
    resultats = relationship("QuizResult", back_populates="quiz", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Quiz(id={self.id}, titre={self.titre}, module={self.module}, source={self.source})>"


class QuizResult(Base):
    """
    Quiz result model storing student quiz attempts.
    """
    __tablename__ = "quiz_resultats"

    id = Column(Integer, primary_key=True, index=True)
    etudiant_id = Column(Integer, ForeignKey("etudiants.id", ondelete="CASCADE"), nullable=False, index=True)
    quiz_id = Column(Integer, ForeignKey("quiz.id", ondelete="CASCADE"), nullable=False, index=True)
    score = Column(Float, nullable=False)  # 0-100
    temps_reponse = Column(Integer, nullable=False)  # in seconds
    reponses = Column(JSON, nullable=True)  # Detailed student answers
    date_tentative = Column(DateTime, default=lambda: datetime.now(UTC), nullable=False, index=True)

    # --- Dynamic-feedback columns (NEW for Phase 2 Step 1) ---
    # Detailed evaluation per question : [{question_id, is_correct, ...}]
    evaluation_detaillee = Column(JSON, nullable=True)
    # Feedback card generated by the LLM after submission
    feedback_card = Column(JSON, nullable=True)

    # Relationships
    quiz = relationship("Quiz", back_populates="resultats")

    def __repr__(self):
        return f"<QuizResult(id={self.id}, etudiant_id={self.etudiant_id}, quiz_id={self.quiz_id}, score={self.score})>"
