"""
English content for Module 4 (Solving Non-linear Equations).

Writes title_en / body_en on the SAME Content nodes as the French version.
Node id pattern: "content_<concept_short>_<level>".

Concepts covered (4 concepts x 3 levels = 12 Content nodes):
  - concept_bissection
  - concept_fixed_point
  - concept_newton_raphson
  - concept_secant

Usage: python scripts/seed_content_module4_en.py
"""
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.graph.neo4j_connection import neo4j_conn

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


CONTENTS = [
    # --- concept_bissection ---
    {
        "concept_id": "concept_bissection",
        "level": "simplified",
        "title": "Bisection method (intuition)",
        "body": """# Bisection method - Simplified version

**Goal**: find a root of $f(x) = 0$, i.e. a number $x$ such that $f(x) = 0$.

## Core idea

If $f$ is continuous and $f(a)$, $f(b)$ have **opposite signs**, then there is at least one root between $a$ and $b$ (intermediate value theorem).

**Strategy**: cut the interval in half and keep the half that contains the root.

## Algorithm in 3 steps

1. Compute the midpoint $m = (a + b) / 2$
2. Look at the sign of $f(m)$:
   - If $f(m) = 0$, we found the root
   - If $f(a)$ and $f(m)$ have opposite signs, root is in $[a, m]$
   - Else it is in $[m, b]$
3. Repeat with the new smaller interval

## Example

Find the root of $f(x) = x^2 - 2$ (which is $\\sqrt{2} \\approx 1.414$):
- $a = 1$, $b = 2$, $f(1) = -1 < 0$, $f(2) = 2 > 0$ -> root in $[1, 2]$
- $m = 1.5$, $f(1.5) = 0.25 > 0$ -> root in $[1, 1.5]$
- $m = 1.25$, $f(1.25) = -0.4375 < 0$ -> root in $[1.25, 1.5]$
- ... converges to 1.414

## Pros / cons

- ✅ **Always converges** if $f$ is continuous
- ✅ Very simple to implement
- ❌ **Slow**: gains 1 bit per iteration (~10 iterations for 3 digits)
""",
    },
    {
        "concept_id": "concept_bissection",
        "level": "standard",
        "title": "Bisection method",
        "body": """# Bisection method

## Hypotheses

Let $f : [a, b] \\to \\mathbb{R}$ be a **continuous** function with $f(a) \\cdot f(b) < 0$. The intermediate value theorem guarantees at least one root $x^* \\in (a, b)$.

## Algorithm

```
while (b - a) > tolerance:
    m = (a + b) / 2
    if f(m) = 0: return m
    if f(a) * f(m) < 0: b = m
    else:               a = m
return (a + b) / 2
```

## Convergence

At iteration $k$, the interval has width $(b - a)/2^k$. The error is bounded by:

$$|x_k - x^*| \\le \\frac{b - a}{2^{k+1}}$$

This is **linear convergence**: factor 2 per iteration, about **1 bit per iteration** (3.3 iterations per decimal digit).

## Iterations needed for precision $\\epsilon$

$$k \\ge \\log_2\\!\\left(\\frac{b - a}{\\epsilon}\\right) - 1$$

Example: for $\\epsilon = 10^{-6}$ on $[0, 1]$, about 20 iterations.

## Limitations

- Requires an initial **bracket** $[a, b]$ with sign change
- **Slow** compared to Newton-Raphson (which is quadratic)
- Does not work for double roots ($f$ does not change sign)
""",
    },
    {
        "concept_id": "concept_bissection",
        "level": "rigorous",
        "title": "Bisection: rigorous analysis",
        "body": """# Bisection: rigorous analysis

## Convergence theorem

**Theorem**: If $f \\in C^0([a, b])$ with $f(a) f(b) < 0$, then the sequence $(c_k)$ generated by bisection where $c_k = (a_k + b_k)/2$ satisfies:

$$\\lim_{k \\to \\infty} c_k = x^*, \\quad |c_k - x^*| \\le \\frac{b - a}{2^{k+1}}$$

where $x^*$ is a root of $f$ in $[a, b]$.

**Proof**: the sequences $(a_k)$ and $(b_k)$ are monotonic and bounded, hence converge to the same limit $x^*$ (since $b_k - a_k \\to 0$). By continuity and sign preservation, $f(x^*) = 0$.

## Comparison with Newton-Raphson

| Method | Convergence order | Hypotheses |
|--------|-------------------|------------|
| Bisection | Linear ($q = 2$) | $f$ continuous, bracket |
| Newton-Raphson | Quadratic | $f \\in C^2$, $f'(x^*) \\ne 0$, $x_0$ close |
| Secant | Super-linear ($q \\approx 1.618$) | $f \\in C^2$, two initial iterates |

## Optimised variants

- **Regula falsi** (false position): linear interpolation between $f(a)$ and $f(b)$ instead of midpoint. Faster in practice but can stagnate.
- **Illinois method**: regula falsi variant that avoids stagnation.
- **Brent's method**: combines bisection + secant + inverse quadratic interpolation. Default algorithm in `scipy.optimize.brentq`.

## Stopping criterion

Several choices:
- **Interval width**: $b_k - a_k < \\epsilon$ (safest)
- **Relative error**: $|c_{k+1} - c_k| / |c_k| < \\epsilon$
- **Residual**: $|f(c_k)| < \\delta$ (warning: not enough alone for functions with small derivative)

## Robustness vs speed

Bisection is the **most robust** algorithm for continuous real functions: it **always** converges. However, for ill-conditioned problems we prefer hybrid algorithms (bisection + Newton).
""",
    },

    # --- concept_fixed_point ---
    {
        "concept_id": "concept_fixed_point",
        "level": "simplified",
        "title": "Fixed-point iteration (intuition)",
        "body": """# Fixed-point iteration - Simplified version

**Idea**: instead of solving $f(x) = 0$ directly, we **transform** the problem.

We rewrite the equation as $x = g(x)$ for a well-chosen function $g$. A solution is called a **fixed point** of $g$: a number that does not change when we apply $g$.

## Algorithm

Pick a starting point $x_0$ and iterate:

$$x_{k+1} = g(x_k)$$

If $g$ is well chosen, the sequence converges to the fixed point $x^*$ such that $x^* = g(x^*)$.

## Example

To solve $x^2 - 2 = 0$ (so $x = \\sqrt{2}$), we can rewrite:
$$x = g(x) = \\frac{1}{2}\\left(x + \\frac{2}{x}\\right)$$

(this is Heron's formula, 2000 years old)

With $x_0 = 1$:
- $x_1 = 0.5(1 + 2) = 1.5$
- $x_2 = 0.5(1.5 + 1.333) = 1.4166$
- $x_3 = 1.41421...$ (already $\\sqrt{2}$ to 5 digits!)

## When it works / when it doesn't

**It converges** if the slope $|g'(x^*)| < 1$ near the fixed point.
**It diverges** if $|g'(x^*)| > 1$: the sequence drifts away.

That is why **the choice of $g$ is crucial**: the same equation $f(x) = 0$ can give several possible $g$, some converge, others don't.
""",
    },
    {
        "concept_id": "concept_fixed_point",
        "level": "standard",
        "title": "Fixed-point iteration",
        "body": """# Fixed-point iteration

## Definition

A **fixed point** of $g : I \\to I$ is a point $x^* \\in I$ such that $g(x^*) = x^*$.

To solve $f(x) = 0$, reformulate as $x = g(x)$ with $g(x) = x - h(x) \\cdot f(x)$ for some non-zero $h$.

## Banach fixed-point theorem

If $g$ is **contractive** on $[a, b]$, i.e. there is $L \\in [0, 1)$ such that:

$$|g(x) - g(y)| \\le L |x - y| \\quad \\forall x, y \\in [a, b]$$

then:
1. There is a **unique** fixed point $x^* \\in [a, b]$
2. The sequence $x_{k+1} = g(x_k)$ converges to $x^*$ for every $x_0 \\in [a, b]$
3. The error satisfies $|x_k - x^*| \\le L^k |x_0 - x^*|$

## Practical criterion

For $g \\in C^1$: if $|g'(x^*)| < 1$, the fixed point is **locally attractive**.

- $|g'(x^*)| < 1$: convergence (linear order)
- $|g'(x^*)| > 1$: divergence
- $|g'(x^*)| = 1$: borderline (may or may not converge)

## Example: equation $x = \\cos(x)$

Let $g(x) = \\cos(x)$. We have $g'(x) = -\\sin(x)$.

The fixed point is $x^* \\approx 0.7391$ (intersection of $y = x$ and $y = \\cos x$).

$g'(x^*) = -\\sin(0.7391) \\approx -0.674$, so $|g'(x^*)| < 1$: it converges.

```
x0 = 1
x1 = cos(1) = 0.5403
x2 = cos(0.5403) = 0.8576
x3 = cos(0.8576) = 0.6543
...
xn -> 0.7391
```

## Convergence rate

Convergence order is **linear** with factor $|g'(x^*)|$. Smaller $|g'(x^*)|$ means faster convergence.

Special case: if $g'(x^*) = 0$, convergence becomes **quadratic** (this is exactly what happens with Newton-Raphson, which is a special case of fixed-point iteration).
""",
    },
    {
        "concept_id": "concept_fixed_point",
        "level": "rigorous",
        "title": "Fixed-point theory",
        "body": """# Fixed-point theory

## Banach contraction theorem

Let $(X, d)$ be a **complete** metric space. If $T : X \\to X$ is a **contraction** (there exists $L < 1$ with $d(T(x), T(y)) \\le L d(x, y)$ for all $x, y$), then:

1. **Existence and uniqueness**: there is a unique $x^* \\in X$ with $T(x^*) = x^*$
2. **Global convergence**: for every $x_0$, the sequence $x_{k+1} = T(x_k)$ converges to $x^*$
3. **Speed**: $d(x_k, x^*) \\le \\frac{L^k}{1 - L} d(x_1, x_0)$

## Local convergence ($C^1$ case)

If $g \\in C^1$ with $|g'(x^*)| < 1$, there is a neighbourhood $V$ of $x^*$ stable under $g$ such that the sequence $x_{k+1} = g(x_k)$ converges to $x^*$ for every $x_0 \\in V$.

**Proof**: by continuity of $g'$, there is $\\delta > 0$ with $|g'(x)| \\le L < 1$ on $V = [x^* - \\delta, x^* + \\delta]$. Then $g$ is contractive on $V$: apply Banach.

## Order of convergence

Let $e_k = x_k - x^*$. For $g \\in C^p$ with $g'(x^*) = g''(x^*) = \\dots = g^{(p-1)}(x^*) = 0$ and $g^{(p)}(x^*) \\ne 0$:

$$e_{k+1} \\sim \\frac{g^{(p)}(x^*)}{p!} \\, e_k^p$$

Convergence of **order $p$**.

- $p = 1$: linear (generic case)
- $p = 2$: quadratic (Newton-Raphson)
- $p = 3$: cubic (Halley's method)

## Application to Newton-Raphson

Newton-Raphson is the iteration $x_{k+1} = x_k - f(x_k)/f'(x_k)$, which is the fixed point of:

$$g(x) = x - \\frac{f(x)}{f'(x)}$$

Compute $g'$:

$$g'(x) = 1 - \\frac{f'(x)^2 - f(x) f''(x)}{f'(x)^2} = \\frac{f(x) f''(x)}{f'(x)^2}$$

At the root $x^*$, $f(x^*) = 0$, so $g'(x^*) = 0$. **This is what makes Newton quadratic.**

## Acceleration: Aitken's algorithm

If $(x_k)$ converges linearly to $x^*$, the **Aitken-accelerated** sequence:

$$y_k = x_k - \\frac{(x_{k+1} - x_k)^2}{x_{k+2} - 2 x_{k+1} + x_k}$$

converges faster to $x^*$. Combined with fixed-point iteration, this gives **Steffensen's method** (quadratic convergence).
""",
    },

    # --- concept_newton_raphson ---
    {
        "concept_id": "concept_newton_raphson",
        "level": "simplified",
        "title": "Newton-Raphson (intuition)",
        "body": """# Newton-Raphson method - Simplified version

**Goal**: find a root of $f(x) = 0$ very fast.

## The geometric idea

From a point $x_k$, look at the **tangent** to the curve $y = f(x)$ at that point. The tangent is a straight line. Find **where this line crosses the x-axis** and call that point $x_{k+1}$.

That is the new estimate. Repeat from $x_{k+1}$.

## The formula

$$x_{k+1} = x_k - \\frac{f(x_k)}{f'(x_k)}$$

## Why does it work?

The tangent to the curve at $(x_k, f(x_k))$ has equation:
$$y = f(x_k) + f'(x_k)(x - x_k)$$

It crosses the x-axis when $y = 0$, giving $x = x_k - f(x_k)/f'(x_k)$.

## Example: $\\sqrt{2}$

We want $f(x) = x^2 - 2 = 0$. The derivative is $f'(x) = 2x$.

Iteration: $x_{k+1} = x_k - \\frac{x_k^2 - 2}{2 x_k} = \\frac{x_k}{2} + \\frac{1}{x_k}$

With $x_0 = 1$:
- $x_1 = 0.5 + 1 = 1.5$
- $x_2 = 0.75 + 0.667 = 1.4167$
- $x_3 = 1.41421...$ ✓

**3 iterations** for 5 exact digits. Much faster than bisection.

## Pros / cons

- ✅ **Very fast**: quadratic convergence (number of correct digits doubles each iteration)
- ❌ Requires **computing the derivative** $f'$
- ❌ Can **diverge** if $x_0$ is poorly chosen
- ❌ Problem if $f'(x_k) = 0$ (division by zero)
""",
    },
    {
        "concept_id": "concept_newton_raphson",
        "level": "standard",
        "title": "Newton-Raphson method",
        "body": """# Newton-Raphson

## Formula

$$x_{k+1} = x_k - \\frac{f(x_k)}{f'(x_k)}$$

## Derivation

We look for a zero of $f$. Near $x_k$, the Taylor expansion gives:

$$f(x) \\approx f(x_k) + f'(x_k)(x - x_k)$$

Solving this linear approximation gives $x = x_k - f(x_k)/f'(x_k)$, which becomes the new iterate.

## Quadratic convergence

**Theorem**: If $f \\in C^2$ near a simple root $x^*$ ($f(x^*) = 0$, $f'(x^*) \\ne 0$), and if $x_0$ is close enough to $x^*$, then:

$$|x_{k+1} - x^*| \\le C |x_k - x^*|^2 \\quad \\text{where} \\quad C = \\frac{|f''(x^*)|}{2 |f'(x^*)|}$$

**Conclusion**: the number of correct digits **doubles** at every iteration. Typically 5-7 iterations suffice for machine precision.

## Stopping criterion

Several criteria:
- **Relative error**: $|x_{k+1} - x_k| / |x_{k+1}| < \\epsilon$
- **Residual**: $|f(x_{k+1})| < \\delta$
- **Combined**: both

## Problematic cases

| Issue | Symptom | Fix |
|-------|---------|-----|
| $f'(x_k) = 0$ | Division by zero | Hybrid method (bisection + Newton) |
| Double root | Linear instead of quadratic convergence | Modified Newton: $x_{k+1} = x_k - 2 f / f'$ |
| Bad initial guess | Divergence or cycle | Bracket with bisection then Newton |
| Oscillation | Infinite loop | Damping: $x_{k+1} = x_k - \\alpha f / f'$ with $\\alpha < 1$ |

## Variant: modified Newton-Raphson

For roots of multiplicity $m$, quadratic convergence is restored by:

$$x_{k+1} = x_k - m \\frac{f(x_k)}{f'(x_k)}$$
""",
    },
    {
        "concept_id": "concept_newton_raphson",
        "level": "rigorous",
        "title": "Newton-Raphson: full analysis",
        "body": """# Newton-Raphson: full analysis

## Local convergence theorem

Let $f \\in C^2$ near a simple root $x^*$ (i.e. $f(x^*) = 0$ and $f'(x^*) \\ne 0$). Then there exists $\\delta > 0$ such that for every $x_0 \\in [x^* - \\delta, x^* + \\delta]$, the sequence $x_{k+1} = x_k - f(x_k)/f'(x_k)$ satisfies:

$$|x_{k+1} - x^*| \\le C |x_k - x^*|^2, \\quad C = \\frac{|f''(x^*)|}{2 |f'(x^*)|}$$

## Proof

Taylor expansion of $f$ to order 2 around $x_k$:

$$0 = f(x^*) = f(x_k) + f'(x_k)(x^* - x_k) + \\frac{f''(\\xi_k)}{2}(x^* - x_k)^2$$

with $\\xi_k$ between $x_k$ and $x^*$. Hence:

$$x^* - x_k = -\\frac{f(x_k)}{f'(x_k)} - \\frac{f''(\\xi_k)}{2 f'(x_k)}(x^* - x_k)^2$$

And $x_{k+1} = x_k - f(x_k)/f'(x_k)$, so:

$$x_{k+1} - x^* = \\frac{f''(\\xi_k)}{2 f'(x_k)} (x_k - x^*)^2$$

This proves quadratic convergence near $x^*$.

## Kantorovich theorem (semi-local convergence)

Stronger than local convergence: does not assume knowledge of $x^*$.

If $f \\in C^2$ and there exist $x_0$, $\\beta$, $\\eta$, $L$ with:
- $|f(x_0) / f'(x_0)| \\le \\eta$
- $|f''(x)| \\le L$ for $|x - x_0| \\le 2\\eta$
- $|f'(x_0)| \\ge \\beta > 0$
- $h := \\beta L \\eta < 1/2$

then Newton's sequence converges to a root $x^*$ with $|x_k - x^*| \\le 2\\eta (2h)^{2^k - 1}$.

## Basin of attraction and chaos

For complex polynomials, the **basin of attraction** of each root is fractal (Newton sets). Example: $z^3 - 1 = 0$ produces the famous Newton fractal with 3 interlaced basins.

## Derived methods

### Modified Newton (multiple roots)

For a root of multiplicity $m$: $x_{k+1} = x_k - m f / f'$. Quadratic convergence restored.

### Halley's method (order 3)

Also uses $f''$:
$$x_{k+1} = x_k - \\frac{2 f f'}{2 (f')^2 - f f''}$$

Cubic convergence but higher cost per iteration.

### Quasi-Newton (Broyden)

Approximates $f'$ via divided differences to avoid analytical computation. Generalises secant to multidimensional.

## Application to optimisation

To minimise $g$, look for $g'(x) = 0$ and apply Newton:
$$x_{k+1} = x_k - \\frac{g'(x_k)}{g''(x_k)}$$

This is Newton's method **for optimisation** (cf. Module 3).
""",
    },

    # --- concept_secant ---
    {
        "concept_id": "concept_secant",
        "level": "simplified",
        "title": "Secant method (intuition)",
        "body": """# Secant method - Simplified version

**Problem with Newton-Raphson**: it requires computing $f'(x)$. Sometimes $f'$ is:
- Very hard to compute
- Not accessible (e.g. if $f$ is given by a program)

**Secant idea**: replace the derivative with an **approximation** using two previous points.

## The formula

Instead of the tangent (Newton), we use the **secant line** between two points $(x_{k-1}, f(x_{k-1}))$ and $(x_k, f(x_k))$.

Slope approximation:
$$f'(x_k) \\approx \\frac{f(x_k) - f(x_{k-1})}{x_k - x_{k-1}}$$

Hence the formula:

$$x_{k+1} = x_k - f(x_k) \\cdot \\frac{x_k - x_{k-1}}{f(x_k) - f(x_{k-1})}$$

## Comparison with Newton

| | Newton | Secant |
|---|---|---|
| Derivative $f'$ | Required | **Not needed** |
| Initialisation | 1 point | 2 points |
| Convergence | Quadratic (order 2) | Super-linear (order $\\sim 1.618$) |
| Practical speed | Faster | Slightly slower |

## Why the golden ratio?

The convergence order of the secant is $\\varphi = (1 + \\sqrt{5})/2 \\approx 1.618$, the **golden ratio**. Slightly worse than Newton (order 2) but much better than bisection (order 1).

In practice, since we don't compute $f'$, **each iteration is cheaper**: the secant can be globally **more efficient** than Newton if $f'$ is expensive.

## Example

For $f(x) = x^2 - 2 = 0$ with $x_0 = 1$, $x_1 = 2$:
- $x_2 = 2 - (4 - 2)(2 - 1)/(4 - (-1)) = 2 - 0.4 = 1.6$
- $x_3 = 1.6 - (0.56)(1.6 - 2)/(0.56 - 2) = 1.4286$
- $x_4 = 1.4146$ etc.

Converges to $\\sqrt{2}$ almost as fast as Newton.
""",
    },
    {
        "concept_id": "concept_secant",
        "level": "standard",
        "title": "Secant method",
        "body": """# Secant method

## Formula

From two consecutive iterates $x_{k-1}$ and $x_k$:

$$x_{k+1} = x_k - f(x_k) \\frac{x_k - x_{k-1}}{f(x_k) - f(x_{k-1})}$$

## Geometric interpretation

This is the root of the line through $(x_{k-1}, f(x_{k-1}))$ and $(x_k, f(x_k))$ — hence the name **secant** (which crosses the curve).

## Super-linear convergence

**Theorem**: If $f \\in C^2$ near a simple root $x^*$, and if the initial iterates are close enough to $x^*$, then the secant converges with order $\\varphi = (1 + \\sqrt{5})/2 \\approx 1.618$:

$$|x_{k+1} - x^*| \\sim C |x_k - x^*|^{\\varphi}$$

Between linear (1) and quadratic (2).

## Comparison with Newton-Raphson

| Criterion | Secant | Newton |
|-----------|--------|--------|
| Cost per iteration | 1 evaluation of $f$ | 1 eval $f$ + 1 eval $f'$ |
| Order | $\\sim 1.618$ | 2 |
| **Total cost for precision $\\epsilon$** | Often lower | Higher if $f'$ is expensive |

If evaluating $f$ is cheap but $f'$ is very expensive, **secant beats Newton**.

## Link with divided differences

The approximated slope $\\frac{f(x_k) - f(x_{k-1})}{x_k - x_{k-1}}$ is the **first-order divided difference** $f[x_{k-1}, x_k]$. The secant method is therefore:

$$x_{k+1} = x_k - \\frac{f(x_k)}{f[x_{k-1}, x_k]}$$

The discrete analogue of Newton-Raphson.

## Variants

- **Regula falsi** (false position): combines secant with bracketing (always keeps a sign change). More robust but can stagnate.
- **Steffensen's method**: $x_{k+1} = x_k - f(x_k)^2 / (f(x_k + f(x_k)) - f(x_k))$, order 2 without computing $f'$.
- **Muller's method**: uses 3 points and fits a parabola. Convergence order $\\approx 1.84$.

## Practical implementation

```python
def secant(f, x0, x1, tol=1e-10, max_iter=50):
    f0, f1 = f(x0), f(x1)
    for k in range(max_iter):
        if abs(f1 - f0) < 1e-15:
            break  # avoid division by zero
        x2 = x1 - f1 * (x1 - x0) / (f1 - f0)
        if abs(x2 - x1) < tol:
            return x2
        x0, f0 = x1, f1
        x1, f1 = x2, f(x2)
    return x1
```
""",
    },
    {
        "concept_id": "concept_secant",
        "level": "rigorous",
        "title": "Secant: rigorous analysis",
        "body": """# Secant: rigorous analysis

## Convergence theorem

Let $f \\in C^2$ near a simple root $x^*$ ($f(x^*) = 0$, $f'(x^*) \\ne 0$). If $x_0, x_1$ are close enough to $x^*$, the secant sequence satisfies:

$$|x_{k+1} - x^*| \\sim \\left|\\frac{f''(x^*)}{2 f'(x^*)}\\right|^{(\\varphi - 1)/(\\varphi + 1)} |x_k - x^*|^{\\varphi}$$

where $\\varphi = (1 + \\sqrt{5})/2$ is the golden ratio.

## Order derivation

The error $e_k = x_k - x^*$ approximately satisfies:

$$e_{k+1} \\approx C \\, e_k \\, e_{k-1}$$

If $e_{k+1} \\sim e_k^p$, then $e_k^p \\sim e_k \\cdot e_{k-1}$, so $e_k^{p-1} \\sim e_{k-1}$, i.e. $e_k \\sim e_{k-1}^{1/(p-1)}$. Also $e_k \\sim e_{k-1}^p$. Hence $p = 1/(p - 1)$, $p^2 - p - 1 = 0$, $p = \\varphi$.

## Asymptotic cost

The **amortised cost** for precision $\\epsilon$ with one evaluation of $f$ per iteration is:

$$\\text{total cost} \\sim \\frac{\\log(1/\\epsilon)}{\\log \\varphi} \\approx \\frac{\\log(1/\\epsilon)}{0.481}$$

For Newton with eval $f$ + $f'$ per iteration:

$$\\text{total cost} \\sim 2 \\cdot \\frac{\\log(1/\\epsilon)}{\\log 2} \\approx \\frac{\\log(1/\\epsilon)}{0.347}$$

**Secant is more efficient** if $f'$ costs more than $0.44 \\cdot $ the cost of $f$.

## Hybrid methods

Practical algorithms combine several methods:

### Brent's method

Used in `scipy.optimize.brentq`:
1. Maintains a bracket $[a, b]$ with sign change (bisection)
2. Tries a **secant** or **inverse quadratic interpolation** step if it lies inside the bracket
3. Otherwise falls back to bisection (guarantees convergence)

Combines **bisection's reliability** with **secant's speed**.

### Dekker's method

Earlier variant of Brent. Same principle.

### Ridders's algorithm

Combines secant with an exponential transformation to improve convergence near roots.

## Multidimensional generalisation: Broyden

To solve $F(\\mathbf{x}) = \\mathbf{0}$ with $F : \\mathbb{R}^n \\to \\mathbb{R}^n$, **Broyden's method** approximates the Jacobian $J$ from previous iterates (rank-1 update):

$$B_{k+1} = B_k + \\frac{(\\Delta F_k - B_k \\Delta x_k) \\Delta x_k^T}{\\Delta x_k^T \\Delta x_k}$$

where $\\Delta x_k = x_{k+1} - x_k$ and $\\Delta F_k = F(x_{k+1}) - F(x_k)$.

This is the multidimensional generalisation of the secant. Super-linear convergence, $O(n^2)$ cost per iteration instead of $O(n^3)$ for multidimensional Newton.

## Link with Krylov methods

In very large dimension (millions of variables), we use **Krylov methods** (GMRES, Bi-CGSTAB) which never store $J$ explicitly and only use matrix-vector products. These methods are generalisations of the secant adapted to giant linear systems arising from linearisation.
""",
    },
]


def main() -> None:
    inserted = 0
    for c in CONTENTS:
        rows = neo4j_conn.run_query(
            "MATCH (c:Concept {id: $cid}) RETURN c.id AS id",
            {"cid": c["concept_id"]},
        )
        if not rows:
            logger.warning("Concept %s not found, skip", c["concept_id"])
            continue

        content_id = f"content_{c['concept_id'].replace('concept_', '')}_{c['level']}"

        neo4j_conn.run_write_query(
            """
            MATCH (c:Concept {id: $cid})
            MERGE (ct:Content {id: $content_id})
            ON CREATE SET
                ct.level = $level,
                ct.title_en = $title,
                ct.body_en = $body,
                ct.title = $title,
                ct.body = $body
            ON MATCH SET
                ct.level = $level,
                ct.title_en = $title,
                ct.body_en = $body
            MERGE (c)-[:HAS_CONTENT]->(ct)
            """,
            {
                "cid": c["concept_id"],
                "content_id": content_id,
                "level": c["level"],
                "title": c["title"],
                "body": c["body"],
            },
        )
        inserted += 1
        logger.info("Inserted EN content for %s (%s)", c["concept_id"], c["level"])

    logger.info("Total EN contents (Module 4) inserted/updated : %d", inserted)


if __name__ == "__main__":
    main()
