version: '3.8'

services:
  # 1. Le cerveau (Votre base de données Graphe)
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474" # Pour voir l'interface visuelle
      - "7687:7687" # Pour connecter Python plus tard
    environment:
      - NEO4J_AUTH=neo4j/monmotdepasse123

  # 2. Le registre des étudiants (Votre base de données Relationnelle)
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=monmotdepasse123
      - POSTGRES_DB=adaptive_learning