# ============================================================
# Pydantic Schemas — Dynamic Quiz + Feedback Card
# ============================================================
# This file defines the "shape" of the data exchanged between the
# frontend and the backend for the DYNAMIC QUIZ module.
#
# Difference with the old quiz.py (static) :
# - Here the questions are GENERATED by the AI on each call
# - The submission response contains a detailed FEEDBACK CARD
#   that explains the student's mistakes
# ============================================================
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


# ============================================================
# 1. QUESTION GENERATED BY THE AI
# ============================================================
class GeneratedQuestion(BaseModel):
    """
    A question produced by the LLM.

    Two supported formats :
    - MCQ : 4 options, only one correct (type="mcq")
    - Open : free answer, evaluated by the LLM (type="open")
    """

    id: int = Field(..., description="Identifiant séquentiel (1..N)")
    type: Literal["mcq", "open", "true_false", "numeric"] = Field(
        "mcq", description="Format de la question"
    )
    question: str = Field(..., description="Énoncé de la question (LaTeX autorisé)")
    options: list[str] | None = Field(
        None, description="Options pour QCM (4 en général)"
    )
    # correct_answer and explanation are HIDDEN from the frontend during the quiz
    correct_answer: str | None = Field(
        None, description="Réponse correcte (uniquement dans le backend)"
    )
    explanation: str | None = Field(
        None, description="Explication pédagogique (après soumission)"
    )
    concept_id: str | None = Field(
        None, description="ID Neo4j du concept ciblé"
    )
    # For numeric questions: accepted absolute gap when grading.
    tolerance: float | None = Field(
        None, description="Tolerance de correction pour les questions numeriques"
    )
    difficulty: Literal["facile", "moyen", "difficile"] = "moyen"
    language: Literal["en", "fr"] = "en"


class StudentFacingQuestion(BaseModel):
    """Question sent to the frontend, WITHOUT the correct answer."""

    id: int
    type: Literal["mcq", "open", "true_false", "numeric"]
    question: str
    options: list[str] | None = None
    difficulty: Literal["facile", "moyen", "difficile"] = "moyen"
    language: Literal["en", "fr"] = "en"


# ============================================================
# 2. INCOMING REQUESTS
# ============================================================
class QuizGenerateRequest(BaseModel):
    """POST /quiz-ai/generate — generation parameters."""

    concept_id: str | None = Field(
        None,
        description="ID Neo4j du concept ciblé (si omis, on devine depuis topic)",
    )
    topic: str | None = Field(
        None,
        description="Sujet en langue naturelle si concept_id non fourni",
    )
    n_questions: int = Field(
        5, ge=3, le=10, description="Nombre de questions (3 à 10)"
    )
    difficulty: Literal["auto", "facile", "moyen", "difficile"] = Field(
        "auto",
        description="'auto' = déduit depuis la maîtrise de l'étudiant",
    )
    question_types: list[Literal["mcq", "open", "true_false", "numeric"]] = Field(
        default_factory=lambda: ["mcq", "true_false"],
        description="Types de questions à mélanger",
    )
    use_llm: bool = Field(
        False,
        description="Si True, genere via Gemma (lent ~30s, variantes experimentales). Si False (defaut), pioche dans la banque hand-curated (instantane).",
    )
    language: Literal["en", "fr"] | None = None
    # Dual pedagogical mode :
    #   "adaptive" : updates the mastery on submit (official progression)
    #   "practice" : free training, does NOT affect the mastery
    mode: Literal["adaptive", "practice"] = Field(
        "adaptive",
        description=(
            "'adaptive' = mode parcours (met a jour la maitrise). "
            "'practice' = entrainement libre (sans impact sur la progression)."
        ),
    )


class StudentAnswer(BaseModel):
    """A student answer for a question."""

    question_id: int
    answer: str = Field(..., description="Réponse brute (texte ou option cliquée)")


class QuizSubmitRequest(BaseModel):
    """POST /quiz-ai/{quiz_id}/submit — quiz submission."""

    answers: list[StudentAnswer]
    language: Literal["en", "fr"] | None = None
    temps_reponse: int = Field(
        ..., ge=0, description="Durée totale en secondes"
    )
    # (12/05/2026) Allows the student to switch to practice mode AT THE MOMENT
    # of submitting, even if the quiz was generated in adaptive. Use case :
    # the student clicks "Go to quizzes" from /path (adaptive mode by
    # default), starts the quiz, realizes they are not ready, and wants
    # to finish without impacting their mastery. The toggle in the UI sends
    # this value. If None -> we respect the Quiz's original mode.
    mode_override: Literal["adaptive", "practice"] | None = Field(
        None,
        description="Override le mode du quiz au moment du submit",
    )


# ============================================================
# 3. OUTGOING RESPONSES
# ============================================================
class QuizGenerateResponse(BaseModel):
    """Fresh generated quiz — sent to the frontend for display."""

    quiz_id: int
    titre: str
    module: str
    difficulte: str
    concept_id: str | None
    concept_name: str | None
    questions: list[StudentFacingQuestion]
    n_questions: int
    language: Literal["en", "fr"] = "en"
    # Quiz mode : useful for the frontend to display the
    # "this quiz does not count towards your progression" banner in practice mode.
    mode: Literal["adaptive", "practice"] = "adaptive"
    date_creation: datetime

    model_config = {"from_attributes": True}


class QuestionEvaluation(BaseModel):
    """Detailed evaluation of a question after submission."""

    question_id: int
    question: str
    student_answer: str
    correct_answer: str
    is_correct: bool
    partial_credit: float = Field(0.0, ge=0.0, le=1.0)
    explanation: str = ""
    concept_id: str | None = None


class FeedbackCard(BaseModel):
    """
    The post-quiz feedback card.

    This is the most important pedagogical deliverable : it explains
    TO THE STUDENT why they made mistakes, on which concepts they have
    gaps, and what to review next.
    """

    score: float = Field(..., ge=0.0, le=100.0, description="Score sur 100")
    n_correct: int
    n_total: int
    temps_reponse: int
    grade_label: str  # "Excellent", "Good", "To review", etc.
    summary: str  # Summary in 2-3 sentences
    strengths: list[str] = Field(
        default_factory=list, description="Concepts bien maîtrisés"
    )
    weaknesses: list[str] = Field(
        default_factory=list, description="Concepts à revoir"
    )
    mistakes_detail: list[str] = Field(
        default_factory=list,
        description="Explication pédagogique par erreur",
    )
    next_steps: list[str] = Field(
        default_factory=list, description="Actions recommandées"
    )
    recommended_concepts: list[str] = Field(
        default_factory=list, description="IDs Neo4j à réviser"
    )


class QuizSubmitResponse(BaseModel):
    """Response after submission : feedback card + detail per question."""

    attempt_id: int
    quiz_id: int
    score: float
    feedback_card: FeedbackCard
    evaluations: list[QuestionEvaluation]
    date_tentative: datetime
    # Quiz mode at submission (echo). In "practice" mode, the frontend
    # must display a "this quiz does not count towards your progression"
    # banner and hide the mastery delta.
    mode: Literal["adaptive", "practice"] = "adaptive"
    # List of concepts whose mastery was updated (empty in practice).
    # Useful to show "+12% Lagrange, +8% Newton-Raphson" on the result page.
    mastery_updated: list[str] = Field(default_factory=list)


class AttemptSummary(BaseModel):
    """History row (list of attempts)."""

    id: int
    quiz_id: int
    quiz_titre: str
    score: float
    temps_reponse: int
    date_tentative: datetime
    grade_label: str | None = None

    model_config = {"from_attributes": True}
